name: E2E Full Suite (Non-blocking)

on:
  schedule:
    # Run daily at 03:00 UTC for broad coverage with DB
    - cron: "0 3 * * *"
  workflow_dispatch: {}

# Avoid overlapping scheduled runs
concurrency:
  group: e2e-full-schedule
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    # Non-blocking by design: surface failures but don't fail the check suite
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        shard: ["1/4", "2/4", "3/4", "4/4"]

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: tdp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/tdp_test?schema=public
      NODE_ENV: test
      NEXTAUTH_SECRET: test-secret-for-e2e-testing-only
      # Use database-backed paths in app and tests
      E2E_SKIP_DB: "0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Prepare database
        run: |
          npx prisma migrate deploy
          if [ -f prisma/seed.ts ] || [ -f prisma/seed.js ]; then npm run prisma:seed || true; fi

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (Shard ${{ matrix.shard }})
        run: |
          set -o pipefail
          SAFE="${{ matrix.shard }}/"
          SAFE=${SAFE//\//_}
          # Chromium-only for daily coverage; cross-browser covered weekly
          npx playwright test --project=chromium --reporter=line --shard=${{ matrix.shard }} 2>&1 | tee "ci_e2e_${SAFE}.log"

      - name: Upload shard logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-e2e-logs-${{ strategy.job-index }}
          path: |
            ci_e2e_*.log
            test-results/**
          retention-days: 5

      - name: Upload Playwright HTML report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ci-e2e-report-${{ strategy.job-index }}
          path: |
            playwright-report/**
          retention-days: 5
